export {default as Home} from './Home'
export {default as Genres} from './Genres'
export {default as Popular} from './movies/Popular'
export {default as Toprated} from './movies/Toprated'
export {default as Person} from './person/Person'
export {default as PersonId} from './person/PersonId'